title: George Liu
tagline: Product-Minded Developer
description: >- # this means to ignore newlines for the value below
  Get the latest updates from George Liu regarding recent projects,
  learning goals, puns, and reflections on life, entrepreneurship, and
  software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gliu20.github.io"

sass:
  style: compressed

exclude: [docs]
paginate: 10
paginate_path: /blog/page/:num/

lsi: true
timezone: America/Toronto
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /:collection/:name/
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:slug/
  - scope:
      path: ""
      type: "puns" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:categories/:slug/ # de-emphasize dates which aren't important
      # puns are always relevant :)
# below this are all auto generated by the redirects page
# this just needs to be copy-pasted in here
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: learning/_posts/2021-01-07-how-we-re-all-entrepreneurs.md
    values:
      redirect_from:
        - /2021/01/07/how-we-re-all-entrepreneurs.html
  - scope:
      path: _puns/2020-09-25-punderline-66.md
    values:
      redirect_from:
        - /2020/09/25/punderline-66.html
  - scope:
      path: _puns/2020-09-18-punderline-65.md
    values:
      redirect_from:
        - /2020/09/18/punderline-65.html
  - scope:
      path: _puns/2020-09-11-punderline-64.md
    values:
      redirect_from:
        - /2020/09/11/punderline-64.html
  - scope:
      path: _puns/2020-09-04-punderline-63.md
    values:
      redirect_from:
        - /2020/09/04/punderline-63.html
  - scope:
      path: _puns/2020-08-28-punderline-62.md
    values:
      redirect_from:
        - /2020/08/28/punderline-62.html
  - scope:
      path: _puns/2020-08-21-punderline-61.md
    values:
      redirect_from:
        - /2020/08/21/punderline-61.html
  - scope:
      path: _puns/2020-08-14-punderline-60.md
    values:
      redirect_from:
        - /2020/08/14/punderline-60.html
  - scope:
      path: _puns/2020-08-07-punderline-59.md
    values:
      redirect_from:
        - /2020/08/07/punderline-59.html
  - scope:
      path: _puns/2020-07-31-punderline-58.md
    values:
      redirect_from:
        - /2020/07/31/punderline-58.html
  - scope:
      path: _puns/2020-07-24-punderline-57.md
    values:
      redirect_from:
        - /2020/07/24/punderline-57.html
  - scope:
      path: _puns/2020-07-17-punderline-56.md
    values:
      redirect_from:
        - /2020/07/17/punderline-56.html
  - scope:
      path: _puns/2020-07-10-punderline-55.md
    values:
      redirect_from:
        - /2020/07/10/punderline-55.html
  - scope:
      path: _puns/2020-07-03-punderline-54.md
    values:
      redirect_from:
        - /2020/07/03/punderline-54.html
  - scope:
      path: _puns/2020-06-26-punderline-53.md
    values:
      redirect_from:
        - /2020/06/26/punderline-53.html
  - scope:
      path: _puns/2020-06-19-punderline-52.md
    values:
      redirect_from:
        - /2020/06/19/punderline-52.html
  - scope:
      path: _puns/2020-06-12-punderline-51.md
    values:
      redirect_from:
        - /2020/06/12/punderline-51.html
  - scope:
      path: _puns/2020-05-29-punderline-50.md
    values:
      redirect_from:
        - /2020/05/29/punderline-50.html
  - scope:
      path: _puns/2020-05-22-punderline-49.md
    values:
      redirect_from:
        - /2020/05/22/punderline-49.html
  - scope:
      path: _puns/2020-05-15-punderline-48.md
    values:
      redirect_from:
        - /2020/05/15/punderline-48.html
  - scope:
      path: _puns/2020-05-08-punderline-47.md
    values:
      redirect_from:
        - /2020/05/08/punderline-47.html
  - scope:
      path: _puns/2020-05-01-punderline-46.md
    values:
      redirect_from:
        - /2020/05/01/punderline-46.html
  - scope:
      path: _puns/2020-04-29-punderline-45.md
    values:
      redirect_from:
        - /2020/04/29/punderline-45.html
  - scope:
      path: _puns/2020-04-24-punderline-44.md
    values:
      redirect_from:
        - /2020/04/24/punderline-44.html
  - scope:
      path: _puns/2020-04-17-punderline-43.md
    values:
      redirect_from:
        - /2020/04/17/punderline-43.html
  - scope:
      path: _puns/2020-04-10-punderline-42.md
    values:
      redirect_from:
        - /2020/04/10/punderline-42.html
  - scope:
      path: _puns/2020-04-03-punderline-41.md
    values:
      redirect_from:
        - /2020/04/03/punderline-41.html
  - scope:
      path: _puns/2020-03-27-punderline-40.md
    values:
      redirect_from:
        - /2020/03/27/punderline-40.html
  - scope:
      path: programming/_posts/2020-03-23-why-you-should-make-your-own-css-framework.md
    values:
      redirect_from:
        - /2020/03/23/why-you-should-make-your-own-css-framework.html
  - scope:
      path: _puns/2020-03-20-punderline-39.md
    values:
      redirect_from:
        - /2020/03/20/punderline-39.html
  - scope:
      path: _puns/2020-03-13-punderline-38.md
    values:
      redirect_from:
        - /2020/03/13/punderline-38.html
  - scope:
      path: _puns/2020-03-06-punderline-37.md
    values:
      redirect_from:
        - /2020/03/06/punderline-37.html
  - scope:
      path: _puns/2020-03-01-punderline-36.md
    values:
      redirect_from:
        - /2020/03/01/punderline-36.html
  - scope:
      path: _puns/2020-02-28-punderline-35.md
    values:
      redirect_from:
        - /2020/02/28/punderline-35.html
  - scope:
      path: _puns/2020-02-28-punderline-34.md
    values:
      redirect_from:
        - /2020/02/28/punderline-34.html
  - scope:
      path: _puns/2020-02-28-punderline-33.md
    values:
      redirect_from:
        - /2020/02/28/punderline-33.html
  - scope:
      path: _puns/2020-02-28-punderline-32.md
    values:
      redirect_from:
        - /2020/02/28/punderline-32.html
  - scope:
      path: _puns/2020-02-25-punderline-31.md
    values:
      redirect_from:
        - /2020/02/25/punderline-31.html
  - scope:
      path: _puns/2020-02-10-punderline-30.md
    values:
      redirect_from:
        - /2020/02/10/punderline-30.html
  - scope:
      path: _puns/2020-02-10-punderline-29.md
    values:
      redirect_from:
        - /2020/02/10/punderline-29.html
  - scope:
      path: _puns/2020-02-10-punderline-28.md
    values:
      redirect_from:
        - /2020/02/10/punderline-28.html
  - scope:
      path: _puns/2020-02-07-punderline-27.md
    values:
      redirect_from:
        - /2020/02/07/punderline-27.html
  - scope:
      path: _puns/2020-02-07-punderline-26.md
    values:
      redirect_from:
        - /2020/02/07/punderline-26.html
  - scope:
      path: _puns/2020-02-07-punderline-25.md
    values:
      redirect_from:
        - /2020/02/07/punderline-25.html
  - scope:
      path: _puns/2020-02-07-punderline-24.md
    values:
      redirect_from:
        - /2020/02/07/punderline-24.html
  - scope:
      path: _puns/2020-02-07-punderline-23.md
    values:
      redirect_from:
        - /2020/02/07/punderline-23.html
  - scope:
      path: _puns/2020-02-07-punderline-22.md
    values:
      redirect_from:
        - /2020/02/07/punderline-22.html
  - scope:
      path: _puns/2020-02-07-punderline-21.md
    values:
      redirect_from:
        - /2020/02/07/punderline-21.html
  - scope:
      path: _puns/2020-02-07-punderline-20.md
    values:
      redirect_from:
        - /2020/02/07/punderline-20.html
  - scope:
      path: _puns/2020-02-06-punderline-19.md
    values:
      redirect_from:
        - /2020/02/06/punderline-19.html
  - scope:
      path: _puns/2020-02-06-punderline-18.md
    values:
      redirect_from:
        - /2020/02/06/punderline-18.html
  - scope:
      path: _puns/2020-02-06-punderline-17.md
    values:
      redirect_from:
        - /2020/02/06/punderline-17.html
  - scope:
      path: _puns/2020-02-06-punderline-16.md
    values:
      redirect_from:
        - /2020/02/06/punderline-16.html
  - scope:
      path: _puns/2020-02-06-punderline-15.md
    values:
      redirect_from:
        - /2020/02/06/punderline-15.html
  - scope:
      path: _puns/2020-02-06-punderline-14.md
    values:
      redirect_from:
        - /2020/02/06/punderline-14.html
  - scope:
      path: _puns/2020-02-06-punderline-13.md
    values:
      redirect_from:
        - /2020/02/06/punderline-13.html
  - scope:
      path: _puns/2020-02-06-punderline-12.md
    values:
      redirect_from:
        - /2020/02/06/punderline-12.html
  - scope:
      path: _puns/2020-02-06-punderline-11.md
    values:
      redirect_from:
        - /2020/02/06/punderline-11.html
  - scope:
      path: _puns/2020-02-06-punderline-10.md
    values:
      redirect_from:
        - /2020/02/06/punderline-10.html
  - scope:
      path: _puns/2020-02-05-punderline-9.md
    values:
      redirect_from:
        - /2020/02/05/punderline-9.html
  - scope:
      path: _puns/2020-02-05-punderline-8.md
    values:
      redirect_from:
        - /2020/02/05/punderline-8.html
  - scope:
      path: _puns/2020-02-05-punderline-7.md
    values:
      redirect_from:
        - /2020/02/05/punderline-7.html
  - scope:
      path: _puns/2020-02-05-punderline-6.md
    values:
      redirect_from:
        - /2020/02/05/punderline-6.html
  - scope:
      path: _puns/2020-02-05-punderline-5.md
    values:
      redirect_from:
        - /2020/02/05/punderline-5.html
  - scope:
      path: _puns/2020-02-05-punderline-3.md
    values:
      redirect_from:
        - /2020/02/05/punderline-3.html
  - scope:
      path: _puns/2020-02-05-punderline-2.md
    values:
      redirect_from:
        - /2020/02/05/punderline-2.html
  - scope:
      path: _puns/2020-02-05-punderline-1.md
    values:
      redirect_from:
        - /2020/02/05/punderline-1.html
  - scope:
      path: programming/_posts/2020-01-04-what-i-learned-winning-stuyhacks-ix.md
    values:
      redirect_from:
        - /2020/01/04/what-i-learned-winning-stuyhacks-ix.html
  - scope:
      path: learning/_posts/2020-01-01-my-goals-and-why-i-dont-have-resolutions.md
    values:
      redirect_from:
        - /2020/01/01/my-goals-and-why-i-dont-have-resolutions.html
  - scope:
      path: programming/_posts/2019-12-08-nyc-disrupt-hackathon.md
    values:
      redirect_from:
        - /2019/12/08/nyc-disrupt-hackathon.html
  - scope:
      path: programming/_posts/2019-11-05-midway-a-case-study-in-ux.md
    values:
      redirect_from:
        - /2019/11/05/midway-a-case-study-in-ux.html
  - scope:
      path: programming/_posts/2019-10-24-midway-reaches-a-hundred-users.md
    values:
      redirect_from:
        - /2019/10/24/midway-reaches-a-hundred-users.html
  - scope:
      path: programming/_posts/2019-08-27-midway-through-the-years.md
    values:
      redirect_from:
        - /2019/08/27/midway-through-the-years.html
  - scope:
      path: programming/_posts/2019-07-12-gradetree-a-tool-for-calculating-weighted-averages.md
    values:
      redirect_from:
        - /2019/07/12/gradetree-a-tool-for-calculating-weighted-averages.html
  - scope:
      path: programming/_posts/2019-06-26-polydice-a-better-way-to-generate-passwords.md
    values:
      redirect_from:
        - /2019/06/26/polydice-a-better-way-to-generate-passwords.html
  - scope:
      path: programming/_posts/2019-05-12-timescend-updates.md
    values:
      redirect_from:
        - /2019/05/12/timescend-updates.html
  - scope:
      path: programming/_posts/2019-02-20-new-logo-midway.md
    values:
      redirect_from:
        - /2019/02/20/new-logo-midway.html
  - scope:
      path: programming/_posts/2018-12-09-timescend-a-new-tool-to-fight-procrastination.md
    values:
      redirect_from:
        - /2018/12/09/timescend-a-new-tool-to-fight-procrastination.html
  - scope:
      path: programming/_posts/2018-03-26-midway-updates.md
    values:
      redirect_from:
        - /2018/03/26/midway-updates.html
  - scope:
      path: programming/_posts/2018-03-09-start-of-midway.md
    values:
      redirect_from:
        - /2018/03/09/start-of-midway.html

collections:
  projects:
    output: true
  puns:
    output: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
