title: George Liu
tagline: Product-Minded Developer
description: >- # this means to ignore newlines for the value below
  Get the latest updates from George Liu regarding recent projects,
  learning goals, puns, and reflections on life, entrepreneurship, and
  software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gliu20.github.io"

sass:
  style: compressed

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:slug/
  - scope:
      path: "puns" 
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:categories/:slug/ # de-emphasize dates which aren't important
      # puns are always relevant :)
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  projects:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
