collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
url: "https://gliu20.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
