name: Deploy Jekyll Site

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      env:
        GH_USER: gliu20
        GH_EMAIL: 24921711+gliu20@users.noreply.github.com
        SOURCE_BRANCH: main
        TARGET_BRANCH: deploy
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 -R /srv/jekyll && npm install && apk add --no-cache gsl-dev && bundle install && bundle exec jekyll build --future"
        rm -rf docs && mv _site docs
        cd docs/assets/images
        find * -type f -exec convert {} -resize 10000@\> xs/{} \; \
        -exec convert {} -resize 100000@\> sm/{} \; \
        -exec convert {} -resize 500000@\> md/{} \; \
        -exec convert {} -resize 1500000@\> lg/{} \; \
        -exec convert {} -resize 5000000@\> xl/{} \;
        cd ../../assets/puns
        find * -type f -exec convert {} -resize 10000@\> xs/{} \; \
        -exec convert {} -resize 100000@\> sm/{} \; \
        -exec convert {} -resize 500000@\> md/{} \; \
        -exec convert {} -resize 1500000@\> lg/{} \; \
        -exec convert {} -resize 5000000@\> xl/{} \;
        cd ../../../
        git config user.name "$GH_USER"
        git config user.email "$GH_EMAIL"
        git rm -r --cached .
        git add docs
        NOW=$(TZ="EST" date)
        git commit -m "Deploy generated on $NOW"
        git push -f origin $SOURCE_BRANCH:$TARGET_BRANCH
