name: Deploy Jekyll Site

env:
  GH_USER: gliu20
  GH_EMAIL: 24921711+gliu20@users.noreply.github.com
  SOURCE_BRANCH: main
  TARGET_BRANCH: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 -R /srv/jekyll && npm install && apk add --no-cache gsl-dev && bundle install && bundle exec jekyll build --future"
        rm -rf docs && mv _site docs
    - name: Resize static image assets
      run: |
        cd docs/assets/images
        sudo mkdir xs
        sudo mkdir sm
        sudo mkdir md
        sudo mkdir lg
        sudo mkdir xl
        find * -type f -exec sudo convert {} -resize 10000@\> xs/{} \; \
        -exec sudo convert {} -resize 100000@\> sm/{} \; \
        -exec sudo convert {} -resize 500000@\> md/{} \; \
        -exec sudo convert {} -resize 1500000@\> lg/{} \; \
        -exec sudo convert {} -resize 5000000@\> xl/{} \;
        cd ../../assets/puns
        sudo mkdir xs
        sudo mkdir sm
        sudo mkdir md
        sudo mkdir lg
        sudo mkdir xl
        find * -type f -exec sudo convert {} -resize 10000@\> xs/{} \; \
        -exec sudo convert {} -resize 100000@\> sm/{} \; \
        -exec sudo convert {} -resize 500000@\> md/{} \; \
        -exec sudo convert {} -resize 1500000@\> lg/{} \; \
        -exec sudo convert {} -resize 5000000@\> xl/{} \;
        cd ../../../
    - name: Push changes to deploy branch
      run: |
        git config user.name "$GH_USER"
        git config user.email "$GH_EMAIL"
        git rm -r --cached .
        git add docs
        NOW=$(TZ="EST" date)
        git commit -m "Deploy generated on $NOW"
        git push -f origin $SOURCE_BRANCH:$TARGET_BRANCH
