name: Deploy Jekyll Site

env:
  GH_USER: gliu20
  GH_EMAIL: 24921711+gliu20@users.noreply.github.com
  SOURCE_BRANCH: main
  TARGET_BRANCH: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/jekyll:4.2.0 \
        /bin/bash -c "chmod 777 -R /srv/jekyll && npm install && apk add gsl-dev \
        && bundle install && bundle exec jekyll build"
    - name: Move files to_docs
      run: |
        sudo chmod -R a+rwx _site && rm -rf docs && mv _site docs
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Minify html
      run: |
        npm install -g html-minifier
        ./html-minify.sh
    - name: Resize static image assets
      run: |
        cd docs/assets/images
        mkdir xs
        mkdir sm
        mkdir md
        mkdir lg
        mkdir xl
        find * -type f -exec convert {} -resize 10000@\> xs/{} \; \
        -exec convert {} -resize 100000@\> sm/{} \; \
        -exec convert {} -resize 500000@\> md/{} \; \
        -exec convert {} -resize 1500000@\> lg/{} \; \
        -exec convert {} -resize 5000000@\> xl/{} \;
        cd ../../assets/puns
        mkdir xs
        mkdir sm
        mkdir md
        mkdir lg
        mkdir xl
        find * -type f -exec convert {} -resize 10000@\> xs/{} \; \
        -exec convert {} -resize 100000@\> sm/{} \; \
        -exec convert {} -resize 500000@\> md/{} \; \
        -exec convert {} -resize 1500000@\> lg/{} \; \
        -exec convert {} -resize 5000000@\> xl/{} \;
        cd ../../../
    - name: Push changes to deploy branch
      run: |
        git config user.name "$GH_USER"
        git config user.email "$GH_EMAIL"
        git rm -r --cached .
        git add docs
        NOW=$(TZ="EST" date)
        git commit -m "Deploy generated on $NOW"
        git push -f origin $SOURCE_BRANCH:$TARGET_BRANCH
