# This is a basic workflow to help you get started with Actions

name: Audit Website

# Controls when the action will run. 

on:
  push:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# See https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        # no npm install or run build b/c we're assuming everything is already built
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
